### ISSUE TITLE
Provide center/edge toggle when getting Sunrise/Sunset information

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#15]
Consider overloading your getSunriseSunset() method to support the center of the sun...

```
 public static Calendar[] getSunriseSunset(Calendar day, double latitude, double longitude)
 public static Calendar[] getSunriseSunset(Calendar day, double latitude, double longitude, boolean isCentered)
```

This was similarly done with Pyephem; http://rhodesmill.org/pyephem/rise-set.html#computing-twilight

**Comment by caarmen** [comment]
I'm sorry, I don't have the bandwidth for this.

**Comment by robertjliguori** [comment]
Consider keeping the issue open, perhaps someone else will provide the code for the feature.

**Comment by caarmen** [comment]
Transfered to https://github.com/caarmen/SunriseSunsetPlus/issues/9
