### ISSUE TITLE
Add support for magic hours

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#20]
Morning magic hours
Blue hour (from -6° to -4°)
Golden hour (from -4° to 6°)
 
Evening magic hours
Golden hour (from 6° to -4°)
Blue hour (from -4° to -6°)

Reference: http://www.photopills.com/articles/understanding-golden-hour-blue-hour-and-twilights

**Comment by caarmen** [comment]
Not sure what timezone you're in, but over here in UTC+1, it's 2017!!!! Happy New Year!!!!

2017 will be the year to #MakeSunriseSunsetGreatAgain!!!

**Comment by robertjliguori** [comment]
By Atlantic City, NJ... Happy New Year!

**Comment by caarmen** [comment]
I don't think I'll integrate this into the core library.  It's too specific of an application.
It could be part of the examples possibly.

**Comment by robertjliguori** [comment]
It's very popular with photographers... though it would be the same as the others...

	public enum DayPeriod {
		DAY,
		CIVIL_TWILIGHT,
		NAUTICAL_TWILIGHT,
		ASTRONOMICAL_TWILIGHT,
                GOLDEN_HOUR,
                BLUE_HOUR,
		NIGHT
	}

**Comment by caarmen** [comment]
Transfered to https://github.com/caarmen/SunriseSunsetPlus/issues/2
