### ISSUE TITLE
Add support for solstices, equinoxes, perihelion and aphelion 

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#21]
Add support for solstices, equinoxes, perihelion and aphelion

**Comment by caarmen** [comment]
I'm sorry, but this would expand the scope of this simple utility class beyond its initially intended purpose.  I did a quick search and found this java class that might help you: https://github.com/sualeh/sunposition/blob/master/src/main/java/us/fatehi/calculation/Equinox.java

**Comment by caarmen** [comment]
https://github.com/robertjliguori/SunriseSunsetPlus/issues/12
