### ISSUE TITLE
Add Starrise/Starset support for Exoplanets

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#23]
Consider adding support for exoplanets through a StarriseStarset superclass (i.e., a superclass that supports accepting parameters of the general environment).

Required state to be provided by user:
-- starName
-- hasAtmosphere  // to establish the need for twilight information
-- heightOfAtmosphere?  // relative to twilight information
-- radiusOfPlanet    
-- angleOfPlanet?
-- [details of it's orbit?]
-- planetRotationSpeed
-- distanceFromSun
-- starCenterUnderHorizon
-- Calendar *** (This would require custom calendars be implemented through JSR 310)
-- etc

Use case: Gliese 581 C was identified as an exoplanet that could support life considering it's size and distance from it's star.  Fun fact: Gliesians live on Gliese 581 C.

**Comment by caarmen** [comment]
I'm sorry, this project will only remain with earthlings.  I am going to close all the issues in the "galactic domination" milestone.

This was only ever supposed to be a simple utility class for sunrise and sunset.  I don't even remember why I added twilight.  It was only thrown on github for backup, and if anybody ever found it useful, that was a bonus.  I made this little class for a project for a friend, and his project is now defunct.  So basically nobody is using it now :) (except maybe you)

It seems you want to create an new industrialized mega library with support of all types of heavenly bodies and all imaginable types of use cases. 

I'm sorry but I just do not have the bandwidth for this.   Just adding support for the isXYZTwilight methods has taken me all Sunday, and it's not finished.  Unit tests are important and they take the most time.

Good luck :)

**Comment by caarmen** [comment]
I suggest you start your own project.  It can have a maven/gradle dependency on this one for the existing functionality, and you can add all the new wonderful stuff you want to your project :)

**Comment by robertjliguori** [comment]
I thought the 'galactic domination' build was a great idea.  Please consider reopening them.  Because this project is on GitHub, other contributors may chime in with some code contributions.  But I doagree having the core class as a lightweight utility class is a great idea.  I'm going to blog about it, in a few minutes.

**Comment by caarmen** [comment]
Transfered to https://github.com/caarmen/SunriseSunsetPlus/issues/10
