### ISSUE TITLE
Add isTwilight method.

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#3]
Add isTwilight method.

**Comment by caarmen** [comment]
Thanks for the suggestion! I may add a method for each type of twilight, ex:

* `isCivilTwilight()` for between civil and nautical twilight dusk or between nautical twilight and civil twilight dawn, 
* `isNauticalTwilight()` for between nautical and astronomical twilight dusk or between astronomical and nautical twilight dawn, 
* `isAstronomicalTwilight()` for between astronomical twilight dusk and dawn

plus a global one `isTwilight()` which will return true if we're between civil twilight dusk and civil twilight dawn (which covers all twilight) .

**Comment by caarmen** [comment]
Added the new methods `isCivilTwilight()`, ìsNauticalTwilight()` and `isAstronomicalTwilight()`.

The existing `isNight()`, or a combination of these three methods, can be used to know if you're in any of the twilights.

**Comment by caarmen** [comment]
reopening for some fixes

**Comment by caarmen** [comment]
* Added function `isTwilight()` to return true if any of the `isXYZTwilight()` methods return true.
* Changed the implementation of `isNight()` to return true if the given time is after astronomical twilight dusk and astronomical twilight dawn (before it returned true if the given time was between sunset and sunrise)

**Comment by robertjliguori** [comment]
Thanks for the new features. :)
