### ISSUE TITLE
Custom date

### ISSUE THREAD

**Issue by chakib33** [caarmen/SunriseSunset#34]
how can we for example call : 
getSunriseSunset("chosen date instate of today", latitude, longitude)
thank you

**Comment by BoD** [comment]
Hi! The first argument is a `Calendar` which can be changed to represent the date you need.  For example:
```java
Calendar calendar = Calendar.getInstance();
calendar.set(2000, Calendar.JANUARY, 1);
getSunriseSunset(calendar, latitude, longitude);
```
Check out the [Calendar documentation](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html) for other ways you can set the date.

**Comment by chakib33** [comment]
Thank you
