### ISSUE TITLE
I believe your start and end verbage is backwards in your docs; consider using dawn and dusk instead.

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#4]
Astronomical twilight dawn : Tue Dec 27 05:42:34 EST 2016 : ~32 minutes
Nautical twilight dawn     : Tue Dec 27 06:14:46 EST 2016 : ~33 minutes
Civil twilight dawn        : Tue Dec 27 06:47:56 EST 2016 : ~29 minutes
Sunrise                    : Tue Dec 27 07:17:36 EST 2016 : ~570 minutes
Sunset                     : Tue Dec 27 16:48:07 EST 2016 : ~29 minutes
Civil twilight dusk        : Tue Dec 27 17:17:46 EST 2016 : ~33 minutes
Nautical twilight dusk     : Tue Dec 27 17:50:57 EST 2016 : ~32 minutes
Astronomical twilight dusk : Tue Dec 27 18:23:08 EST 2016

**Comment by robertjliguori** [comment]
Snagging Twilight Times with the Java SunriseSunset API
http://robertjliguori.blogspot.com/2016/12/snagging-twilight-times-with-java.html

**Comment by caarmen** [comment]
I believe start and end are correct in the doc. For example, for civil twilight, the "end" is dawn, which is element 0 of the returned array, and the "start" is dusk, which is element 1. This looks consistent with the code snippet on your blog and the output you pasted here. Unless I missed something :-) I looked it over a couple of times just now. 

Maybe dawn and dusk could be clearer than end and start. I'll have to verify that those terms are correct (and not tied specifically to one of the specific types of twilight/sunrise/sunset.)

Thanks for the feedback and the blog!

**Comment by caarmen** [comment]
Ok, looks like I can use dawn and dusk in the doc: I just have to specify the type: "civil dawn", "astronomical dawn" etc. 

https://en.m.wikipedia.org/wiki/Dawn
