### ISSUE TITLE
Support Solar Noon (High Noon / Midday)

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#5]
Add a feature to query solar noon (high noon) for a given  day / location.

**Comment by robertjliguori** [comment]
This gives a rough estimate, but I guess isn't entirely accurate...
```
    public String determineHighNoon(Calendar sunrise, Calendar sunset) {
        Long highNoon = (sunrise.getTime().toInstant().toEpochMilli() + sunset.getTime().toInstant().toEpochMilli()) / 2;
        Instant i = Instant.ofEpochMilli(highNoon);
        LocalDateTime ldt = LocalDateTime.ofInstant(Instant.ofEpochMilli(highNoon), ZoneOffset.systemDefault());
        DateTimeFormatter format
                = DateTimeFormatter.ofPattern("EEE MMM dd hh:mm:ss yyyy");
        return ldt.format(format);
    }
```

**Comment by caarmen** [comment]
Great idea, thanks! I did a quick look at sunrisesunset.com. This is what it has for Paris today:

Sunrise: 8:44am
Solar noon: 12:53pm
Sunset: 5:02pm

Looks like noon is exactly between sunrise and sunset in this example, so hopefully this calculation will be good enough. I'll add unit tests for several locations and days in the year to verify this.

**Comment by caarmen** [comment]
I didn't need to use your suggested calculation (the average of sunrise and sunset).  I was already calculating solar noon in order to calculate sunrise and sunset, so I reused the existing calculation.

**Comment by robertjliguori** [comment]
Thank you for this feature. :)
