### ISSUE TITLE
Update pom.xml with missing elements...

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#6]
-- consider adding description and inception year elements...

    
    <name>lib-sunrise-sunset</name>
    <description>Provides methods to determine the illumination phases of a given location.</description>
    <url>http://rmen.ca</url>
    <inceptionYear>2014</inceptionYear>
 
-- consider adding license info

    <licenses>
        <license>
            <name>TBD</name>
            <url>TBD</url>
            <distribution>TBD</distribution>
            <comments>TBD</comments>
        </license>
    </licenses>

-- consider adding organization, developers and contributors elements as well.

**Comment by caarmen** [comment]
There's no "organization".  :) There's just one person maintaining this "library" as a weekend hobby. Library is a big word too, as it's just a single 380 line java file, which hasn't had anything new added in nearly 2 years.  In fact I basically just threw this on github to have a place in the cloud to back it up.  Didn't think anybody was even using it. 

Thanks for the enthusiasm though.

**Comment by caarmen** [comment]
Added this to the `publish.xml` file which is the one that is deployed to bintray and jcenter.

**Comment by robertjliguori** [comment]
Thanks for the update. :)
