### ISSUE TITLE
Support twilight/sunrise/sunset reporting for Mars

### ISSUE THREAD

**Issue by robertjliguori** [caarmen/SunriseSunset#7]
Wikipedia states, "Twilight on Mars is longer than on Earth, lasting for up to two hours before sunrise or after sunset. Dust high in the atmosphere scatters light to the night side of the planet. Similar twilights are seen on Earth following major volcanic eruptions." -- https://en.wikipedia.org/wiki/Twilight

Consider supporting twilight on mars.  This would require some thought and discussion as Nautical Twilight  is surely in the context of activities on earth... however it's apparently tied to the visibility of the horizon.  So terminology would need to be bounced around.

**Comment by caarmen** [comment]
Transfered to https://github.com/caarmen/SunriseSunsetPlus/issues/6
